services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ArnaudDelgerie\AiToolAgent\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    ArnaudDelgerie\AiToolAgent\Resolver\ClientResolver:
        arguments:
            - !tagged_iterator 'ai_tool_agent.ai_client'

    ArnaudDelgerie\AiToolAgent\Resolver\ToolFunctionResolver:
        arguments:
            - !tagged_iterator 'ai_tool_agent.tool_function_manager'
            - !tagged_iterator 'ai_tool_agent.console_tool_function_manager'